# Generated by Django 5.2.9 on 2025-12-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
