# Generated by Django 5.2.9 on 2026-01-03 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_planner', '0004_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
