# Generated by Django 5.2.9 on 2026-01-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_planner', '0006_task_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='response',
            new_name='answer',
        ),
    ]
